### ISSUE TITLE
can octave use it?

### ISSUE THREAD

**Issue by Freed-Wu** [DrosteEffect/BrewerMap#2]
can make it as a package of octave? if octave user can also use it, it will be better!

**Comment by DrosteEffect** [comment]
I just tested BREWERMAP on Octave 4.4.0, all of the examples work as documented. As far as I can tell there are no functions or syntaxes used in BREWERMAP that would prevent it working in Octave.

BREWERMAP_VIEW will not work as it uses handles to nested functions, which are not supported in Octave. Note that BREWERMAP_VIEW is a supplementary function which is not required for using BREWERMAP.
