### ISSUE TITLE
brewermap_view for colororder

### ISSUE THREAD

**Issue by Niklas123Niklas** [DrosteEffect/BrewerMap#3]
Hi there,

thanks for providing this nice Matlab addon. I wanted to ask for afeature that would be nice to have:
Is it possible to use brewermap_view also to change to colororder instead of the colormap? I am mostly using lineplots, that do not use colormap, but the colororder property. 

Adding that would be great, if it is possible.

Cheers,
Niklas

Edit: Looking at your code, I just changed line 268 of brewermap_view to:
colororder(hgv(k),brewermap(nmr(k),bmvName()));

Is it possible to somehow implement this nicely to the matlab addon?

**Comment by beddalumia** [comment]
You may want to take a look at [colorlab](https://github.com/bellomia/colorlab), which allows you wrap this brewer implementation (and many other colormap providers) in a convenient `set_colororder(name, N, {varargin})`. Although N is optional you would need to provide it in this case, as Steven's brewermap function (which is internally called) sets the default N to the Matlab built-in, which is not suitable for use as colororder. But yes, `set_colororder('PuRd', 7)` would totally allow to replace standard Matlab colororder with the fancy purple-to-red Brewer palette. You'll find even an example with `'Spectral'` in the README! 🤠

**Comment by beddalumia** [comment]
(of course if you really want a GUI option we don't have it either at the moment, the `paletteshow.brewer` method behaves exactly as `brewermap_view` here and Steven is definitely much better qualified to retouch these outstanding call-back sorceries 🙂)

**Comment by DrosteEffect** [comment]
_"Although N is optional you would need to provide it in this case, as Steven's brewermap function (which is internally called) sets the default N to the Matlab built-in, which is not suitable for use as colororder"_

That is exactly why I provided the N=NaN option, which returns a colormap with exactly as many colors as defines the colorscheme. The Mfile help specifically states that this is _"useful for line ColorOrder"_.

@Niklas123Niklas : I think your request should be easy to add. I will take a look at it in the next few days.

**Comment by DrosteEffect** [comment]
@Niklas123Niklas : I added an optional third input which selects between COLORMAP and COLORORDER. Please give it a try and let me know if it helps.

**Comment by beddalumia** [comment]
@DrosteEffect thanks for pointing that out, I forgot of that detail. I'll update my set_colororder wrapper to handle correctly the brewer case :)

**Comment by Niklas123Niklas** [comment]
Hi there,
thanks for the update! It works perfectly nice! 
Cheers, Niklas
